---
- name: Create /etc/hosts file on managed nodes 
  hosts: all 
  become: true 
  tasks: 
  
    - name: Create hosts file using j2 template 
      template: 
        src: /Users/hayden/development/ansible/templates/hostsfile.j2
        dest: /etc/hosts
