---

- import_playbook: install_base_software_and_enable_services.yml 
- import_playbook: firewall_config.yml
- import_playbook: monthly_backup.yml
- import_playbook: motd_configure.yml
- import_playbook: users.yml
- import_playbook: update.yml
