$ANSIBLE_VAULT;1.1;AES256
63626664666338396531303565363130633464626333623031363137356435336132656365383332
6538643033363361393734666432306638626334353436620a343930326136363736383466356538
32636666616262656539626338656230363736303833646362343430353038343661343238646465
3861363463353166360a356130393234613362636464383034623034636561623936346561323262
63343039633231396137393964626261343062356433376634333136343562333038343561386336
36626565393931643431356161633265653764303333396639343362336365393664616237313631
63333635343466393633643232373637313863656164666262646234303463306337323834376337
63366636643136626235643963633035343836383230646266623863383165393135633762396131
32376133343031626633373633323434376134333835666134316435353638633030346531333735
64313865326535626434623864646531636232303334363236373765623139303132653931303736
65356562363330343737323237323239346564616233363663333065336564306665643133306339
35653634646336343332623139643138646630363264613330396163663437663030616430623761
31313732303733666136656639656537376335613463633830303461313538636463373566383538
62653263323433616334633031333730363737633330356464353062376535366663633938626436
37663633376338363861663763356363363531636261663136346437303666323632336134303766
30353763626462343464666161643931643030306566353533653139363236396239643663633430
30613963663862393830666664376137336137373532633933343863363533393361646436393135
33363066616366326236373739366432633137343536343566373061333765336239666637386336
39313561646339326639306438383265303266656138326532336665353637373734386635363063
64646431343433396134363931613433343562643562393862663335393862653862386664326330
34323265626632343937313064383639343332333131323035366531323132383230323730383238
37353436386663663864643234353534613834363038613166376333393961316430393436623432
666261316665396438643433613266643464
