---


prod_software:
  - firewalld 
  - autofs
  - lvm2 
  - vim 
  - ansible 
  - git 
  - docker.io
  - podman
  - python3

prod_services: 
  - firewalld 
  - cron.service
  - autofs



ansible_python_interpreter: /usr/bin/python3.13 
